---

on:
  pull_request: {}
  push:
    branches:
      - main

name: CI

jobs:
  build_docker_image:
    name: 'Built test Docker image'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'puppetserver'
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: puppetserver
          tags: 'ci/puppetserver:${{ github.sha }}'
          push: false

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ci/puppetserver:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

  tests:
    needs:
      - build_docker_image
    runs-on: ubuntu-latest
    name: Test suite
    steps:
      - run: echo Test suite completed
